### ISSUE TITLE
have script check if live & dev are the same

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1573]
At more than one point reverts have caused us to have weird code we're not clear on running on live as github starts telling us code is the same when it isn't. This causes immediate & long term issues.

We want to change our process so that we avoid reverts and have reverts mean review, however, as a backstop it should be simple to write a script that manually alerts us if code is not the same on live / dev right after builds.

**Comment by JosephMcArthur** [comment]
Mark, do you think this is still important? And, do you have an estimate for what it would take to do?

My sense is that give we have more smaller repos now... it might be more complex.

**Comment by markmacgillivray** [comment]
I don't think this is so critical now with the different repos for different code. The task of checking if a difference has occurred after a revert can be done with one command on a linux machine, the greater work comes in fixing those differences. I think this issue can be closed without a fix.

**Comment by JosephMcArthur** [comment]
great
