### ISSUE TITLE
Enabling easy setup of CF workers (or equivalent) API and backend

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1757]
We've been discussing routes to people being able to run our new infrastructure themselves as a way to deepen our promise of open source, and as a way to allow others to build off our systems.

The headline take away from one conversation was that to get part of our backend running, the bit running on CF workers we could provide a button to click that would do it: https://developers.cloudflare.com/workers/platform/deploy-button. 

Otherwise, the process would look like:
* Get a workers account
* Clone paradigm
* Clone OAB API repo
* Re-org folder
* Deploy to CF
* [optional] getting a KV store

Which we think will be a fairly quick thing to document / run regardless. 

In either case, we'd want to provide some nod to what you'd think about and use instead of CF workers.

This, we expect, would give you a mostly working version of the API quickly. But, it wouldn't have all the performance of ours (due to no data, everything would be called on the fly), and some missing features (e.g no history / logs).

The next steps in the workflow to forking would be getting a backend server up and running. Broadly, that means:

* Getting a linux server (for instance, from DO) 
* Installing Node.JS & Elastic Search
* Cloning Paradigm (& our API code?)

We can of course document this. But, turns out Digital Ocean has a button too: https://www.digitalocean.com/docs/app-platform/how-to/add-deploy-do-button/. It seems like it has some limitations... but maybe they're okay to live within to offer the simplicity. No idea. Maybe we could get that process down to a few minutes too, and lower some of the skill gaps (e.g I don't know how to manage servers at all, but I've got code running on Heroku with these buttons before).

That would give you some other capabilities, but you'd be missing a lot of data. We have ingest scripts written, so those could be used if pointed at a data dump. That would take some time to literally process, but we'd have jumped over some of the hurdles. 

All in all, this is starting to feel very 'us' as a way to offer this assurance and function to folks. Still needs a lot of exploration though to make sure it all works in reality, but it seems like even if we fall a bit short we have a good goal in mind here.

**Comment by markmacgillivray** [comment]
This issue is covered in work already done in paradigm or to do in issues there.
