### ISSUE TITLE
Automate MAG update from azure

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/discussion#1772]
And deletion once downloaded if possible, due to ridiculous costs.

**Comment by markmacgillivray** [comment]
We're not doing this now until we see how useful it is. If useful we will automate it later.

**Comment by markmacgillivray** [comment]
This may not get done in February either but putting it in February for now to remind me to check on when the next dump from MAG hits azure, and re-evaluate (likely just doing it manually again and moving this out to March, but got to keep it in mind as they charge us to have it sitting there doing nothing).

**Comment by JosephMcArthur** [comment]
MAG is going to be retired by the end of the. I expect this is not useful to automate now. Closing, reopen if you disagree.
