### ISSUE TITLE
Permissions not identifying the lancet papers as journal articles 

### ISSUE THREAD

**Issue by natalianorori** [oaworks/discussion#1806]
While doing permissions checks, I found out that the API is having trouble identifying The Lancet and a couple of ScienceDirect articles as journal articles. I have manually checked them and made sure these are all research articles. This is an issue we've had with The Lancet in the past. 

DOIS and api responses here: https://docs.google.com/spreadsheets/d/1xW8HugJwTK2PyLc2xcbw5OfvBRVysIdQ0pg3Iivrs2w/edit#gid=0

**Comment by JosephMcArthur** [comment]
Does seem to be an issue here. Can you take a look @markmacgillivray?

p.s. Updated name to remove reference to unannounced name

**Comment by markmacgillivray** [comment]
On the new dev API this works. There are a few changes to permissions API on the new code waiting to go out. Let me know when you're happy to push them to live.
