### ISSUE TITLE
Some InstantILL subscription links broken due to extra URL encoding of `&`

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1808]
**Describe the bug**

IUPUI reported some issues with our links to full text. An indicative example is https://ulib.iupui.edu/article/search?doi=10.13005/bpj/1530. Here we correctly ID they have access, but the link doesn't work. 

**To Reproduce**

First get logged in. This must be done via another page for weird reasons:

1. Go to https://proxyauth.uits.iu.edu/auth/ulib.pl?auth=library
2. Login using the credentials I've sent over email

Then,

1. Go to https://ulib.iupui.edu/article/search?doi=10.13005/bpj/1530
2. Click on `Open article in a new tab`
2. See error

`The link you clicked triggered a search in ProQuest that did not find the item you were expecting.
Required link information may be missing or incorrect. Ask your librarian or administrator for help.`

The link provided by their link resolver works fine: https://rx8kl6yf4x.search.serialssolutions.com/?rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&url_ver=Z39.88-2004&rfr_id=info%3Asid%2Fsersol%3ARefinerQuery&SS_ReferentFormat=JournalFormat&SS_LibHash=RX8KL6YF4X&rft.genre=article&rft_id=info%3Adoi%2F10.13005%2Fbpj%2F1530&l=RX8KL6YF4X&SS_doi=10.13005%2Fbpj%2F1530&sid=sersol%3ARefinerQuery

**Expected behavior**

The expected page was: https://www-proquest-com.proxy.ulib.uits.iu.edu/docview/2264144214?accountid=7398

**Additional context**

There are several other examples sent over emails you're cc'ed in.

**Proposed Fix (if available)**

I've done some investigations, and I think I've found the problem. The story so far...

The lookup we did in the `find` for that DOI is:

http://rx8kl6yf4x.openurl.xml.serialssolutions.com/openurlxml?version=1.0&genre=article&&&sid=InstantILL&rft_id=10.13005%2Fbpj%2F1530&atitle=Awareness%20of%20Laser%20Dentistry%20Among%20Dentists%20in%20Tanjore-%20A%20survey&issn=0974-6242%2C2456-2610&title=Biomedical%20and%20Pharmacology%20Journal&publisher=Oriental%20Scientific%20Publishing%20Company&date=2018-07-10&rft.year=2018&aulast=K%2C%20Harini%2C%20Arjunkumar%2C%20Radhika&issue=3&volume=11&pages=1623-1632&

On this page, if you use `<ssopenurl:url type="article">` as we would expect you get to the right result.

I then compared the link given on that page

`https://www.ulib.iupui.edu/cgi-bin/proxy.pl?url=https://gateway.proquest.com/openurl?ctx_ver=Z39.88-2004&res_dat=xri:pqm&rft_val_fmt=ori/fmt:kev:mtx:journal&genre=article&issn=0974-6242&jtitle=Biomedical+%26+pharmacology+journal&volume=11&issue=3&spage=1623&atitle=Awareness+of+Laser+Dentistry+Among+Dentists+in+Tanjore-+A+survey&req_dat=xri:pqm:accountid=7398`

 with what we provide.

`https://www.ulib.iupui.edu/cgi-bin/proxy.pl?url=https://gateway.proquest.com/openurl?ctx_ver=Z39.88-2004&amp;res_dat=xri:pqm&amp;rft_val_fmt=ori/fmt:kev:mtx:journal&amp;genre=article&amp;issn=0974-6242&amp;jtitle=Biomedical+%26+pharmacology+journal&amp;volume=11&amp;issue=3&amp;spage=1623&amp;atitle=Awareness+of+Laser+Dentistry+Among+Dentists+in+Tanjore-+A+survey&amp;req_dat=xri:pqm:accountid=7398`

They are the same, *except*, we have inserted `amp;` where `&` was originally. At this stage, I presumed this was the cause of the error, and that it appeared *we* were doing that.

**Checklist (For internal use)**

* Take a breath. Bugs are okay.
* Stay clear of hangouts

Process checklist:
* Do we want a `fast` first, then a `good` fix? A `good` fix likely involves discussion, and may be slower. A fast fix means whoever is available fixes the problem as best they can immediately without too much consideration for the `good` fix.
- [x] Discussion of solution. Remember, our intuitive fixes may be different (e.g UI centric, backend centric)

Post-fix
- [ ] How can we avoid bugs like this in future?
- [ ] How can we avoid regressions (e.g automated test)

[//]: # "=======================	
**IF USER VISIBLE**
============================"	

Preemptive communications (for high profile bugs):
- [-] Put up a site / page banner (if warrented)
- [-] Put up a tweet (if warrented)
- [-] Put up announcement on Uptimerobot (if warrented)
- [-] Set reminder to keep users up to date

User communications checklist:
- [X] Apologize and empathize. e.g I'm so sorry. This must be such a pain.
- [X] Give a timeline. We'll review this by X. We're working on this ASAP. 
- [X] Confirm understanding of the issue, and request any information required.
- [X] Thank them for letting us know. 
- [X] Can we mitigate without fixing the bug?

**Comment by markmacgillivray** [comment]
Turns out you were right but it wasn't us. The raw xml from serialssolutions has amp; but I assume you looked at it in a web browser which would automatically display it is & for you - but when it was included in the URL, it was the literal string from the XML, which was not & but amp; 

I have added a fix to the new dev API to convert them back to &, and I have tested that it works with the above. 

I'll need to do an update to the new live API, hopefully will get done this weekend or during next week, then this can be closed. I'll assign back to @JosephMcArthur in case you want to do any follow up with the user.

**Comment by JosephMcArthur** [comment]
Is this live?

**Comment by JosephMcArthur** [comment]
@markmacgillivray can you give me an update here please?

**Comment by markmacgillivray** [comment]
It's live
