### ISSUE TITLE
`class="_oab_repo">` doesn't work

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1810]
In ShareYourPaper `<span class="_oab_repo">ScholarWorks</span>` is used to replace ScholarWorks with a repo name set in the config.

However, this doesn't appear to be working at the moment, which means on some screens ScholarWorks can't be updated.

This only affects some screens, as the most prominent screens seem to replace Scholarworks in a different way.

**Comment by markmacgillivray** [comment]
Yeah oddly there was even a comment in there to add that value once the config had been retrieved, but it had never been done. I've added it now on dev and merged it into the develop branch of the website repo. If this sounds like the fix you intended, let me know and I can merge it into master.

**Comment by JosephMcArthur** [comment]
Review here Joe: https://dev.openaccessbutton.org/shareyourpaper/setup#preferences-dark
