### ISSUE TITLE
Discuss old API downtime

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/discussion#1818]
Joe recorded some things working and others not working while the old API was down for a few minutes. He would like to discuss it.

**Comment by JosephMcArthur** [comment]
Moreso, I'm interested in analysis from you on:

   - Why did we go down (you mentioned weird traffic)?
   - Why didn't the "bounce" system (which I tried to use) and any other
   automated systems to resolve downtime work to resolve this?
   - What could we do to avoid this in future?
   - Given many services worked (as far as I could tell), does our
   definition (and therefor, status pages / monitoring etc) of "down" need to
   change? Aka right now it's a "global thing", when actually likely SYP and
   ILL were fine, Find was likely fine, but requests for instance was not.



Joe McArthur
Director / Co-Founder: OA.Works <https://oa.works>
The Open Access Button is now OA.Works! Find out more about our rebrand
<https://blog.oa.works/open-access-button-is-now-oa-works/>.


On Fri, Jul 16, 2021 at 10:52 AM, markmacgillivray ***@***.***

**Comment by markmacgillivray** [comment]
Technically we didn't go down. It was another case of it not responding sometimes to some queries. It was going slow. There was weird traffic at the time but I wasn't able to work out the cause, it may have been ourselves, and that is partly due to our odd position between two system at the moment. Which is also why many things kept working while others didn't - something we're already aware of as a current possibility. The bounce system didn't work because it wasn't down, and bounce can't work when it is down either - the old bounce system can only work in certain circumstances for the old system, and isn't appropriate for the new system.

Our definition of "down" is certainly inaccurate, but that has been the case for a long time. It has already happened that certain things report as down even though they are not, they may just be timing out from a certain location. We definitely have an "Old stuff possibly down" and "new stuff not down" possibility at the moment, which will persist until we decide either to move old stuff to the new code or turn it (or parts of it) off.

Our monitoring is working fine for letting us know of problems - we knew of the problem, it got fixed. I'm not concerned about the definition of down in that sense, because it really doesn't matter. What matters is knowing that there is a situation that needs looked at, and we're already getting that. For the case of what our status pages show publicly, that's different, and would require further work, and deciding what the requirements are for letting people know if certain things are up or down (and keeping in mind that at some point if enough things are down, the status page becomes useless too).

I think we're already doing what we want to do to avoid this in future. The only things left are things that we've already chosen not to prioritise yet, like whether to move or shut down requests, and when to move the "deposit" and other bits that we definitely do need to move. As we said in our discussion yesterday, that's likely to be another 3 to 6 months, so until then we have a slightly vague position such as this, but I don't think there's anything else worth doing - if we were going to put time into it, we'd be better off just prioritising the work to move things off the old system to the new one.

**Comment by JosephMcArthur** [comment]
Understood –– thanks mark!
