### ISSUE TITLE
10.1021/acsinfecdis.1c00276 doesn't work with SYP for unknown reasons

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1820]
**Describe the bug**

Entering 10.1021/acsinfecdis.1c00276 produces "doesn’t look right" response

**To Reproduce**
1. Go to https://shareyourpaper.org/10.1021/acsinfecdis.1c00276
2. See error

**Expected behavior**

Generally speaking, it's expected to run as normal.

This is backed up by doi.org/10.1021/acsinfecdis.1c00276 working. 
Further, https://api.crossref.org/works/10.1021/acsinfecdis.1c00276/agency says it's a crossref DOI. 
However, https://api.crossref.org/works/10.1021/acsinfecdis.1c00276 throws a `Resource not found.` error.

**Additional context**

I was curious what Unpaywall would do, given they're pretty tied to these.

https://api.unpaywall.org/v2/10.1021/acsinfecdis.1c00276?email=joe@openaccessbutton.org seems to return as normal.

**Proposed Fix (if available)**

No idea, I'm stumped. Don't think I've seen this before.

**Comment by markmacgillivray** [comment]
We have seen ones like this before. DOIs are issued in bulk by crossref to publishers etc. Publishers can then assign them to articles, and they can set up the redirect so that the doi.org/... works. However, if they never submit metadata to crossref about the article, then technically it is still "not in crossref" because nobody has told crossref about it. We use the check on the crossref API to determine if it is "in crossref". If we ARE given a DOI, and that DOI is NOT in crossref, then we don't accept it.

We can change that if you want, and accept them anyway.

**Comment by markmacgillivray** [comment]
Note the downside is that some publishers to intentionally use DOIs for junk, and then never submit metadata about them to crossref, so we may return more junk answers. We may also hit unpaywall with more junk DOIs. However if we set up a local copy of unpaywall that's less important. And we can get some metadata back from unpaywall, though not as much. So we could return some answers for DOIs "not in crossref" in this sense, possibly with less metadata than usual, and possibly some that are junk.

**Comment by JosephMcArthur** [comment]
Ah, I see. I guess if we just turned this off the outcome would this would work but some other junk DOIs might make it through the system. So, my mind goes to how might we tell the difference. Unpaywall seems to know... Do you have any idea where Unpaywall got their general metadata from in this case? E.g title, publication date, etc? I thought they'd get that from CrossRef but if Crossref doesn't it then I don't know how they do.

**Comment by markmacgillivray** [comment]
Well it's a fairly new publication, maybe there's a delay between the public crossref API and what paying customers see, and maybe unpaywall pay for it. Or maybe the use additional sources for metadata. Anyway yeah I think we could just allow a check of a DOI against unpaywall even if we don't find it on crossref.

**Comment by JosephMcArthur** [comment]
Given we'll have it locally soon that makes sense as a path forward here.

Do you have a rough estimate for how long this would take to implement?

**Comment by markmacgillivray** [comment]
Not long, half an hour or so.

**Comment by JosephMcArthur** [comment]
Okay, could we do that this week please? Ideally today or tomorrow? Would
be nice to say this is fixed when I meet Gates.

**Comment by markmacgillivray** [comment]
OK, done, on dev and live. I've tested on shareyourpaper.org, looks fine. You can close this unless there's anything else @JosephMcArthur
