### ISSUE TITLE
SYP switches DOI being deposited part way through deposit process

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1822]
**Describe the bug**

Somewhat unsure what the bug is. What Leila sees is described in the title, however, what I see on dev looks different.

For Leila, trying to deposit [Mozaffari-Racetrack-2021.docx](https://github.com/oaworks/discussion/files/6881437/Mozaffari-Racetrack-2021.docx) for `10.1016/j.watres.2021.117220` gives unusual results as described in `Deposit Requires Checking: 10.1086/260600`.

On dev, after uploading the file above at dev.shareyourpaper.org I got a successful upload but the record has poor metadata in the title and other spots. See here: https://sandbox.zenodo.org/record/888150#.YP8wiJP0m3U. So does depositing the same file via https://oaworks.github.io/testing-ground/shareyourpaper/dev/montana?doi=10.1016/j.watres.2021.117220 (which should control for some unusual config issue). A glance at the Crossref metadata (and [ours](https://api.openaccessbutton.org/metadata?doi=10.1016/j.watres.2021.117220)) suggests we should see more complete data.

**To Reproduce**

The issue doesn't replicate on dev, however, it is also not resolved. There appears to be a different problem on dev.

**Expected behavior**

We'd expect this to be deposited into Zenodo with more complete / correct metadata and for behavior to be the same across live & dev.

**Additional context**

There is an email thread about it.

**Comment by markmacgillivray** [comment]
@JosephMcArthur if this is uncommon, how soon do you think it might be that we can refactor deposit into the new API code? Just thinking how much time it's worth spending on this problem if we're soon going to be replacing that code anyway.

**Comment by JosephMcArthur** [comment]
I guess my first question would be, is this uncommon? The second is do you know this is due to deposit code?

I can't right away answer the broader question. We thought it wasn't a priority to move a things would keep working as they were, but that seems like it may not be true. If it's not true, that would of course bump the refactor work up the list.

**Comment by markmacgillivray** [comment]
As we do get the correct metadata to start with, and that can be confirmed on both our old and new systems on both dev and live, the only part of the process that could change the metadata would be the provision of the file to deposit - when we get a file, some more work is done looking into that file, so I'm guessing that is where the issue arises. Since it's only deposit where files get provided, that's why I think the issue is in the deposit code.

As to how often it happens, I've never seen something like this before, so if you haven't either, it's pretty uncommon, at least so far.

**Comment by JosephMcArthur** [comment]
Okay, that all makes sense. Probably the path through here is to do a
manual deposit on Leila's behalf and then keep an eye out for similar
issues. I remember the refactor for this route was connected to lots of
other things and not simple –– so unless we're seeing frequent issues it
would be better to handle later I think.

Does that make sense to you?

Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur



On Tue, Jul 27, 2021 at 12:27 PM, markmacgillivray ***@***.***

**Comment by markmacgillivray** [comment]
Yeah deposit is a bit more complex but will also require stuff we may need to do fairly soon for the gates work. So if we can leave the fixing of this for even a week or two, then at least we'd have a better idea of scheduling for gates work and could decide if it's worth fixing this on old code or prioritising file handling on the new API code development plan. So if a manual solution can work for this particular case just now, that's great, let's leave it a while.

**Comment by markmacgillivray** [comment]
Noting here that the two issues commented from above, #1826 and #1827, along with this issue, may be best solved by moving deposit to the new API, which we will be discussing soon I believe. So I have re-opened this issue as a tracker for that - there may be another one somewhere, or can create a new one and relate this one to the new one. For now, keeping this one as placeholder.
