### ISSUE TITLE
SYP fails to deposit `10.1177/0038038519853109`

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1826]
**To Reproduce**
1. Go to dev.shareyourpaper.org/10.1177/0038038519853109
2. Try to deposit [Article Last Revision The symbolic efficacy of pope Francis.docx](https://github.com/oaworks/discussion/files/6983489/Article.Last.Revision.The.symbolic.efficacy.of.pope.Francis.docx)
3. See `Sorry, we were not able to deposit this paper for you. Please try contacting us directly`

**Expected behavior**

It should be deposited

**Comment by markmacgillivray** [comment]
I tried this and got the "is this a PDF" response. I clicked the "it's an accepted manuscript" and it appeared to work fine. Could this have just been coincidental with #1827

**Comment by JosephMcArthur** [comment]
That seems probable. However, the "this is a pdf" response isn't expected. What I'm worried about is if this is a continued issue with the deposit endpoint as in https://github.com/oaworks/discussion/issues/1822.

**Comment by markmacgillivray** [comment]
See issue #1822 for ongoing tracking of this possible problem
