### ISSUE TITLE
10.1088/1751-8121/ac2476 has no metadata

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1833]
We just got a review deposit `Review Deposit 10.1088/1751-8121/ac2476`.

The email had no metadata in it, which I confirmed at `https://api.openaccessbutton.org/metadata?doi=10.1088/1751-8121/ac2476`.

Crossref has plenty of information about it, see `https://api.crossref.org/works/10.1088/1751-8121/ac2476` and it looks like it was updated about a week ago.

My sense is we should also have that information, why don't we?

**Comment by JosephMcArthur** [comment]
Seeing the same with 10.1016/j.talanta.2021.122922

**Comment by markmacgillivray** [comment]
Nothing new to report here.

**Comment by markmacgillivray** [comment]
These were due to the hand-off between old and new systems caching empty results. That's been cleared now, and /metadata has been routed via the old API to the new one as well. I think it is safe to close this one.
