### ISSUE TITLE
Query to see a full deposit record doesn't return 

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1836]
This is an old and hopefully small bug I've never gotten around to reporting

**Describe the bug**

The link we provide in deposit emails to `Full Deposit API Record(s)` provides a link that doesn't return the deposit records for the DOI in question.

**To Reproduce**

See just about any deposit record. Just forwarded `Successful Deposit: 10.1016/j.irle.2020.105925` where the following link is provided: https://api.openaccessbutton.org/deposited?q=doi:10.1016/j.irle.2020.105925. 

**Expected behavior**

Just records for the DOI in question should be shown.

**Comment by markmacgillivray** [comment]
Nothing new to report here

**Comment by markmacgillivray** [comment]
It looks like this error arises out of the email template. Note you appear to be creating a query URL using the metadata.doi field, so the query url should also use metadata.doi, not just doi. Also to get an exact match it should have quotes around it, like so:

https://api.openaccessbutton.org/deposited?q=metadata.doi:"10.1016/j.irle.2020.105925"

If the template can be fixed, that should resolve this issue.

**Comment by JosephMcArthur** [comment]
Just committed to dev. Can you check it, I'm a little unsure about use of ". 

See https://github.com/oaworks/website/commit/24e19150970d2edd27627d346e8b536800fe4ff7

**Comment by markmacgillivray** [comment]
Since the double quotes are inside double quotes for your href tag you'd need to escape them, which you can do using a \

href="https://api.openaccessbutton.org/deposits?q=metadata.doi:\"{{metadata.doi}}\""

**Comment by markmacgillivray** [comment]
If that doesn't work (can't quite remember how it will get processed) you could use single quotes for the href tag then it shouldn't clash with the double quotes in the href value.
