### ISSUE TITLE
Generally unusual behaviour on 10.1016/j.vaccine.2020.12.031

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1837]
This is related to https://github.com/oaworks/discussion/issues/1835 likely, but it's a less specific report.

**Describe the bug**

On this deposit, I'm see several problems:

* https://github.com/oaworks/discussion/issues/1835
* The file should've been depositable, but it wasn't.
* The email didn't provide any permissions or deposit information.

**To Reproduce**

This should currently still be reproducible from the emails. However, I just manually deposited the content and so that might change.

**Expected behavior**

* The file should've been depositable normally
* The email should've provided permissions and deposit information

**Comment by JosephMcArthur** [comment]
Saw a few more potential examples of this today:

Review Deposit 10.1038/nature20796
Review Deposit 10.1053/j.gastro.2020.07.003
Review Deposit 10.1038/nature13793
Review Deposit 10.1038/s41586-019-1443-5

Which I've sent your way.

Namely, all of these:
> The email didn't provide any permissions or deposit information.
> #1835

If you happen to have something sitting on dev to fix it already (I seem to remember you mentioning you'd fixed some of these issues already) pushing that would be fab.

**Comment by markmacgillivray** [comment]
This is fixed as far as the bad metadata goes, so that just leaves why it was not depositable (which may relate to the bad metadata but could be other things) and why the admin deposit link didn't work (which may also relate to the bad metadata but could be other things). I'll continue looking at those parts.

**Comment by JosephMcArthur** [comment]
If you could take a look tomorrow that would be fab, as this is an issue I'm seeing affect deposits a few times a week.

**Comment by JosephMcArthur** [comment]
Any chance of an update here please?

**Comment by markmacgillivray** [comment]
This one is now also being reviewed as part of #1829, see there for further updates. Will keep this open until that one is closed.

**Comment by markmacgillivray** [comment]
The examples above now appear depositable or already available. I think that means this issue is complete, although I did not try an admin deposit except for the nature one already used in the admin deposit issue.

**Comment by markmacgillivray** [comment]
Just a note to remember this will close with #1829
