### ISSUE TITLE
`Review deposits` without files are generating a lot of non-sense email

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1839]
This has been noted in #1829 with:

> Bad external scripts generating 100k or so emails.

However, breaking out for discussion here.

The script use seems to continue, although it's changed now. Over the weekend I got around 9k emails for what seemed like mostly different DOIs.

While this is confusing usage, I don't think it's problematic usage, the only issue is the emails generated. So, it's worth asking, do we really need emails for review deposits sent via the API and without files? I think likely not. I think we originally had these as part of a broader set of notifications and while the others are helpful and serve their purpose well these don't.

I'd suggest we turn them off. But, @markmacgillivray, maybe you have other thoughts?

**Comment by markmacgillivray** [comment]
Has this solved it? Or are you still getting thousands of emails?
