### ISSUE TITLE
ISSN in DOAJ isn't findable in permissions

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1840]
**Describe the bug**

`1561-8633` is the ISSN in question. It's in DOAJ, see: https://doaj.org/toc/1684-9981. When searched for via the other ISSN in DOAJ it's found (see: https://api.openaccessbutton.org/permissions?issn=1684-9981). And, on that record, you can even see 1561-8633. However, you can't get to the record by directly searching 1561-8633.

**Comment by markmacgillivray** [comment]
This is fixed, was due to a discrepancy in how journal ISSNs are stored between us and our source.
