### ISSUE TITLE
Move email templates from website repo into sheet

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/discussion#1841]
Email templates for the API system are currently in the old website repo:

https://github.com/oaworks/website/tree/develop/emails

That repo will eventually become obsolete, so maintaining the templates there long term is not so suitable. Also as the new API integrates with sheets more easily, we should move any templates that are still going to be needed in future into the sheet that has been made for the purpose. instantill_create and the deposit templates have already been moved for the new API. Any others that are still relevant should be copied across as well. The sheet for this is:

https://docs.google.com/spreadsheets/d/16Qm8n3Rmx3QyttFpSGj81_7T6ehfLAtYRSvmDf3pAzg/edit#gid=0

That sheet should also be moved to a suitable OA.Works folder so that everyone who needs to access it can do so.

**Comment by JosephMcArthur** [comment]
> Any others that are still relevant should be copied across as well

Are you able to check which have actually been used recently?

> That sheet should also be moved to a suitable OA.Works folder so that everyone who needs to access it can do so.

Are you able to do that? Just moving into the shared drive with everything else should be fine.

**Comment by markmacgillivray** [comment]
I don't appear to be able to put that sheet into the shared drive for OAB / OA.Works actually. Are you able to?

I can't check which have been used recently, we can just copy them all across anyway, I just thought if there are definitely ones you know you're not going to need, like if they're for a now-obsolete system we're not going to maintain any more, then we can just not copy those ones.

**Comment by JosephMcArthur** [comment]
I can't because you haven't given more than view access.

Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Done

**Comment by JosephMcArthur** [comment]
Is it just deposit emails using the sheet?

**Comment by markmacgillivray** [comment]
No all templates that you still want to use should go into it. I've reopened it until that's done.

**Comment by JosephMcArthur** [comment]
I've done few, but, the request ones I'm unsure about what is / isn't in use. I may need to ask Natalia which I don't want to do while she's away. Is this a blocker to release of #1829?

**Comment by markmacgillivray** [comment]
Only the ones that you will want the new system to use need to be moved over. So if request isn't going to be moved, there's no point moving any request emails anyway.

**Comment by JosephMcArthur** [comment]
Okay, then we should be good to go
