### ISSUE TITLE
Move embed into separate repo and document it

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/discussion#1842]
In progress, repo created, issue exists until docs (README) done.

**Comment by markmacgillivray** [comment]
This had already been started so I did more work trying to integrate testing of it with the deposit refactor issue, but it would involve too much wrangling of other parts of the old website. So some documentation of the embed in the new separate repo for it may continue over christmas / new year period, but will be switching to doing the permissions refactor stuff first, as Joe requested earlier this week. Early in new year can come back to testing the separated embed.

**Comment by markmacgillivray** [comment]
Code exists in dev on separate repo now, ready for testing on dev. See #1590 for related work.

**Comment by markmacgillivray** [comment]
README still to be done on this, will continue this week and into next, ready for walkthrough with other staff where necessary pretty soon, unless other things take priority. So docs is being done in interim gaps.

**Comment by JosephMcArthur** [comment]
> The above would also relate to the testing of the "new" embed itself (the one that is being separated from the website repo and converted solely to js). In #1842 I have been working through that, the documentation is not done yet but I am up to the point of wanting to test that new embed code on the dev site anyway.

Can we do this testing without affecting the main dev system at the moment? I don't want embed code to become a blocker for release.

**Comment by markmacgillivray** [comment]
Yes but if we push the permissions changes to live the current embed won't know how to handle the changes to the output of permissions checks. So we at least have to make the changes to the old embed that would be necessary to get it to work with the changes to permissions key/value content.

**Comment by JosephMcArthur** [comment]
Okay, what would you propose in order to shorten the time to being able to release permissions / deposit refactors?

**Comment by JosephMcArthur** [comment]
Excellent news

**Comment by markmacgillivray** [comment]
And note https://github.com/oaworks/paradigm/issues/54

**Comment by JosephMcArthur** [comment]
Would be good to know:

1. If this is on dev such that https://dev.shareyourpaper.org (for example) is now using this? Will all embeds on dev use this automatically?
2. If the code is ready to test
3. During testing, what sorts of things might we want to be on the lookout for? Is there anything you've changed that we might want to be on the lookout for?

**Comment by markmacgillivray** [comment]
I haven't connected it up to dev yet, but will do today or tomorrow. Then everything on dev will be using the new embed code instead of the old, automatically.

It is ready to test, the first test will be I'll do the above and see if it runs. If it doesn't I'll make any changes to get it running.

After that, testing is a matter of not noticing anything! It should work exactly as the old one did, including changes made to the old one up to now.

**Comment by JosephMcArthur** [comment]
Excellent thanks

**Comment by markmacgillivray** [comment]
I'd need clarification on what you mean. It's a javascript file, you can use it anywhere you include it. That could be in a local html file, if that's what you mean. But it doesn't do anything useful unless it can reach our API, which is configured to point to our actual running API (or the dev instance). You could change that to point to a local one as well, if you also ran a local copy of the API.

**Comment by JosephMcArthur** [comment]
Hmm, yeah that makes sense. Can the openaccessbutton website be built
locally?

**Comment by markmacgillivray** [comment]
yes, there's a node build script in the repo that builds it wherever you run it. That would require cloning the repo and installing node and probably some node packages, I think the build script explains that in the comments at the top.

Same deal as the embed, you would then have local static files you could look at, but anything that tries to execute an action would need to be able to connect to our running API (unless you run it locally as well and change the config settings to build your local version to point to a local version of the API).

**Comment by JosephMcArthur** [comment]
An update here would be fab Mark. Eloisa is due to start work on the embed
next week (21st), so it would be fab to polish this off this week
(including testing, docs). Is that possible?

**Comment by markmacgillivray** [comment]
I was late finishing it last week because I did the permissions stuff for JCT as well. However I've been doing the testing of this on dev today and should have it working and in its own repo within a few hours. I'm also pushing the updated readme soon. So that should leave the rest of the week for any more eyeball testing you want to do (as previously mentioned, once I have it set up it should just work like the old one, with no visible change).

**Comment by JosephMcArthur** [comment]
No worries, I know you had other stuff on last week :) This sounds fab. LMK when you'd like me to poke around (ideally, automated tests would all be passing before that!).

**Comment by markmacgillivray** [comment]
OK, ghostinspector SYP and instantill tests are passing as much as they did previously, as far as I can tell. Dev sites are using the new separate embed, the repo has a README and comments in the code. You can try anything on dev this week as you normally would, it should behave the same.

**Comment by JosephMcArthur** [comment]
Thanks! I'll endeavor to review at least a bit later today.

**Comment by JosephMcArthur** [comment]
Did a bit of testing, didn't go wild, given all the tests are passing and we're not expecting changes. Let's push live whenever we can.

Re docs. I read them, and had a couple of thoughts:
* Should we make an issue for config simplification? What is holding up simplification?
* Should we consider changing the use of `oab` to `oaw` considering OAworks the new umbrella name (and, `oab` is unlikely to be a standalone tool in this)
* I didn't understanding what the usage of the term `prototype` was referring too.

Of course, the above is all superficial semantics :)

**Comment by markmacgillivray** [comment]
Config simplification depends on us deciding not to need login for those configs, and having the configs come with the requests. We already discussed that in relation to the "moving accounts" issue, so the same work to check who still does it the old way is required. Then once we can be sure configs won't need to be retrieved via the API for a user ID, we could simplify config retrieval in the embed. I'd say this isn't urgent and could be a long way off anyway, as it has to come after all those other steps.

Could change oab to oaw, not too hard. Will do.

"prototype" is a javascript term for adding a function. It doesn't matter, don't worry about it.

**Comment by JosephMcArthur** [comment]
> Config simplification depends on us deciding not to need login for those configs, and having the configs come with the requests. We already discussed that in relation to the "moving accounts" issue, so the same work to check who still does it the old way is required. Then once we can be sure configs won't need to be retrieved via the API for a user ID, we could simplify config retrieval in the embed. I'd say this isn't urgent and could be a long way off anyway, as it has to come after all those other steps.

If there isn't already an issue for the above with some context, can you please me / update one?

> "prototype" is a javascript term for adding a function. It doesn't matter, don't worry about it.

Thought as much :)

**Comment by markmacgillivray** [comment]
I've detailed it in https://github.com/oaworks/embed/issues/1

So I think this issue can close. Re-open if not.

**Comment by markmacgillivray** [comment]
Joe asked why two ghostinspector tests are failing:

https://app.ghostinspector.com/tests/5f23dcc15e12c014aeaefb71
(AAM upload)

https://app.ghostinspector.com/tests/5f22f086bfb7c24532f4581d
(redeposit library default)

This seems to be related to changes for the new embed, but dev is now back to using the old embed, it seems. We closed this issue but have not actually discussed how to start using the embed. So the new embed is done and documented, but is not in use anywhere. The change to dev to allow testing for it has not been factored into any ongoing developments.

So I have re-opened this issue.

Points to consider:

How is the old OAB website (and related ones such as SYP) being maintained now? Are they to stay as is, and who is managing future developments of them? Should they be deploying the same way they currently are, or not? Are they switching to new static sites?

Training on the new embed was meant to take place, but we missed some scheduled meetings due to unavailability / travel / sickness of various people at different times, so I'm not sure what is happening about that now. Should we be using the new embed yet, or not?

If we're not yet using the new embed anywhere, although it is ready to use, should I try putting in a fix for the above two ghost inspector tests onto the old embed code, or the new?

**Comment by JosephMcArthur** [comment]
In https://github.com/oaworks/discussion/issues/1842#issuecomment-1066785948 I asked for the new embed code to be pushed live given we'd tested it above. What would stop us doing that now, and why is dev no longer using the new embed code?

For now, we're keeping the old sites served as is and changing them as little as possible.

**Comment by markmacgillivray** [comment]
Yes, odd, I thought we'd done that too. I'll check what's going on with it.

**Comment by markmacgillivray** [comment]
Investigations so far suggest that it may be due to recent pushes to the develop branch of the website repo. It's possible they overwrote manual configurations I had made to serve the new embed code. Since the embed code is now a separate repo, but we're not doing much to change the old website code, the only way to have the new code served by the old site was to have the old site embed code repointed to the new code on the server machine itself.

About keeping the old website as is with as little change as possible, we do also already have an issue open somewhere about moving how it is served - it is currently on the old noddy OAB server, which after May is not going to be viable. So if the website is not getting moved into netlify or anything else like that, we'll need to move that too. I think we'd briefly discussed just moving that over to the new API machine, but that in itself still wouldn't solve the problem of the old website repo only having the old embed code in it.

So, is anyone else currently scheduled to do any work with the new embed code, and/or the old website? If not, we'd better schedule that into my work asap too, and at least get the old website code updated in some maintainable way that will allow it to serve the new embed code from the new repo (possibly a submodule solution). Otherwise any manual fixes on the server could risk being overwritten if the old website IS actually going to receive changes by git commits pushing new code to whatever server it is running on.

I'm continuing to look into this to see if there was anything else that could have caused it though, these are just possible points to consider that it seemed worth documenting so they're not forgotten either way.

**Comment by markmacgillivray** [comment]
New config setup using nginx to directly serve the new embed from its own repo whenever it is requested via the old openaccessbutton.org, shareyourpaper.org, instantill.org domains. So this will work even if those sites are updated in future. This config has already been put in place on dev, and can go live any time (see #1852 about testing it)

**Comment by markmacgillivray** [comment]
As part of this work I changed the use of oab to oaw in the embed, but this has broken some tests which are looking for class names such as "_oab_inputs". Do you want these tests updateed, or should I revert it back to continuing to use oab instead?

Note, it appears that quite a few other tests also just failed because links to files expected from IUPUI are no longer resolving - not much we can do about that, and I don't know what they're necessary for, so I think you'd have to look at altering those tests.

**Comment by JosephMcArthur** [comment]
I'll update the tests

Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Once you're happy with the test config, this issue can be closed as the work to put it on live has been done.
