### ISSUE TITLE
Use `old_way` to update mailto for `My paper doesn't have a DOI` button

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1845]
As discussed on chat.

**Comment by JosephMcArthur** [comment]
@markmacgillivray can you take a look at this this week please?

**Comment by JosephMcArthur** [comment]
Hmmm, let me be more specific. *after* and only after we ship the refactor live would you be able to look at this please?

**Comment by JosephMcArthur** [comment]
@markmacgillivray got an ETA here? Gates are asking about it. Releasing a fix this week would be ideal.

**Comment by markmacgillivray** [comment]
I already did this in the new separate embed code, but we haven't tested that yet, there's an issue #1842 for it. I have also put it into the old embed code version in the website repo, on the develop branch, and I've pushed that to the repo so you can see the change if you want to. So on the dev site it should already be possible to try it out by changing the config of whichever account it is you're wanting to try this for. Then to release to live it just requires merging the website develop branch. Or we could finish testing the new embed code and make the changes to release that, but that will probably take a bit longer.

**Comment by JosephMcArthur** [comment]
Thanks! Not seeing the change as expected right now. I'm going to send you off the thread a link & username / password (as this is public) so you can see what I'm testing.

Given this is tiny and time sensitive change I'd like to do this in the "old" version and mirror changes in the "new" one. Otherwise, let's avoid any other "feature" changes during the refactor as normal.

**Comment by markmacgillivray** [comment]
The place where you've indicated expecting to see the old_way address is not a place that previously used the old_way value at all. There are indeed multiple other places that use the calculated contact email address, but there were only two that tried to use the old_way value, so those are the only two I changed. Can you list all the locations you expect the old_way value to be used now, if it's an email address? I don't think there's a way I can work out where you expect it to be from looking at the code, apart from looking at where it had previously been used. Once you let me know though, it'll be easy enough to finish this - for example if the answer is just that the "doesn't have a DOI" button should have it, then I can finish it in about ten minutes.

**Comment by JosephMcArthur** [comment]
I think the answer is just `My paper doesn't have a DOI` button as suggested plus whatever was already using `old_way`. I poked around a bit and the places I expected to be using it are using it.

**Comment by markmacgillivray** [comment]
OK, done.
