### ISSUE TITLE
Ingest & enable automatic updates for DOAJ

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1853]
As discussed.

cc @markmacgillivray

**Comment by markmacgillivray** [comment]
This is done, but automation has not been enabled yet while we review what to do with journals index this week. The system is already in place though, so it's just a config option to start automatic updates for this.

Note, it isn't possible to know about DOAJ "in_progress" applications from their public data, so we won't know that. (But the only case where this might matter would be JCT, and they do have access to that data, so we could recommend them to check it themselves).

**Comment by JosephMcArthur** [comment]
Is this being automatically updated? If so, anything else needed before closing?

**Comment by markmacgillivray** [comment]
Nope, but now we're confirmed recent changes are good, I'll turn on automatic updates after the big openalex data load is complete (just waiting to change settings without restarting dev). Then I'll close this.

**Comment by JosephMcArthur** [comment]
Sarah just asked me how often we're planning to sync with DOAJ, Mark, have you decided that yet?

cc @swipperman

**Comment by markmacgillivray** [comment]
Doaj dumps once a week on Sunday so ours will probably run early Monday U.K. morning

**Comment by JosephMcArthur** [comment]
👍 👍 👍 👍 👍
