### ISSUE TITLE
Error with URLs for Wiley in InstantILL

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1854]
Seen two reports of this new from paying InstantILL customers.

From: https://ulib.iupui.edu/article/search (email:`Error with URLs for Wiley in InstantILL`)

> One of our librarians found a glitch in the links InstantILL is providing for Wiley articles, where the provided link gets a 404 error from Wiley. I’ve tested a couple from the American Journal of Industrial Medicine, and it looks like there’s a few characters in the URL different from the links in Google Scholar or the link resolver – 
> 
> **InstantILL search (results in erroneous “Open article in a new tab” link)**
> 
> https://ulib.iupui.edu/article/search?title=Lead%20and%20cancer%20in%20humans:%20Where%20are%20we%20now
> 
> **Link provided by InstantILL (results in 404 error)**
> 
> https://www.ulib.iupui.edu/cgi-bin/proxy.pl?url=https://onlinelibrary.wiley.com/doi/10.1002/1097-0274(200009)38:3&lt;316::AID-AJIM11&gt;3.0.CO;2-P
> 
> **Link resolver link (working):**
> 
> https://rx8kl6yf4x.search.serialssolutions.com/log?L=RX8KL6YF4X&D=SUPJJ&J=AMERIJOUROFIN&P=Link&PT=EZProxy&A=Lead+as+a+carcinogen%3A+Experimental+evidence+and+mechanisms+of+action&H=a1ccfa6f9a&U=https%3A%2F%2Fwww.ulib.iupui.edu%2Fcgi-bin%2Fproxy.pl%3Furl%3Dhttps%3A%2F%2Fonlinelibrary.wiley.com%2Fdoi%2F10.1002%2F1097-0274%28200009%2938%3A3%3C316%3A%3AAID-AJIM11%3E3.0.CO%3B2-P
> 
> **Google Scholar link (working):**
> 
> https://onlinelibrary.wiley.com/doi/abs/10.1002/1097-0274(200009)38:3%3C316::AID-AJIM11%3E3.0.CO;2-P

From: https://www.library.ualberta.ca/services/interlibrary-loan (email:`InstantILL`)

> Searched title: 
> WORKING MEMORY TESTING REVEALS NEUROPLASTICITY ACUTELY AND LONGITUDINALLY AFTER MILD TRAUMATIC BRAIN INJURY (MTBI)
> 
> **Link provided:**
> http://login.ezproxy.library.ualberta.ca/login?url=https://onlinelibrary.wiley.com/resolve/openurl?sid=vendor%3Adatabase&amp;date=2018&amp;issue=S1&amp;genre=journal&amp;issn=0892-6638&amp;volume=32
> 
> Results in:
> 
> https://onlinelibrary-wiley-com.login.ezproxy.library.ualberta.ca/openurl?amp;issue=S1&amp;date=2018&amp;genre=journal&sid=vendor%3Adatabase&amp;volume=32&amp;issn=0892-6638
> 
> Which has the following error page:
> ![image](https://user-images.githubusercontent.com/4953703/161032173-e5ada845-ae36-4d62-9a53-33430ba3c6aa.png)
> 
> A search for the title on this site finds the article and the article page has the following URL:
> 
> https://faseb-onlinelibrary-wiley-com.login.ezproxy.library.ualberta.ca/doi/10.1096/fasebj.2018.32.1_supplement.878.5

**Comment by JosephMcArthur** [comment]
On Monday morning, can I get an update here? Even if it's no progress. Got to keep customers updated.

**Comment by markmacgillivray** [comment]
Yep I've worked out what is causing the issue but haven't put in a fix yet. I may have that done by Monday, or on Monday, will let you know.

**Comment by JosephMcArthur** [comment]
Perfect, thank you. Just knowing that is useful enough –– so if you don't
happen to be able to update on Monday no stress.

Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
For the second, what's the hurdle to testing? Is it access to full text or something like that? We can get credentials.

**Comment by markmacgillivray** [comment]
Would it be possible for someone to check and see if this URL works?

http://login.ezproxy.library.ualberta.ca/login?url=https://onlinelibrary.wiley.com/resolve/openurl?volume=32&issue=S1&issn=0892-6638&sid=vendor%3Adatabase&date=2018&genre=journal

The creds you gave me previously appear to have been for the first, which I have confirmed is fixed on dev. If the above new URL also works, then the second one is also fixed and I can push the fixes to live.

**Comment by JosephMcArthur** [comment]
Yup, done!

Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
Also, if we have a fix for IUPUI then deploying that would be great.

**Comment by JosephMcArthur** [comment]
It opened:

![image](https://user-images.githubusercontent.com/4953703/166476118-2300ce03-bc3f-4375-b08e-cc5a80621354.png)

**Comment by markmacgillivray** [comment]
OK so it looks to me like both these problems are fixed. I'll update live tomorrow, unless I've misunderstood.

**Comment by JosephMcArthur** [comment]
Happy for you to update live.

Given it's hard for us to test these, is there anything you want me to clarify / check with reporters?

**Comment by markmacgillivray** [comment]
Once done we could have the same two raised in this issue checked by the respective users to confirm it worked.

**Comment by JosephMcArthur** [comment]
Cool, will do

Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur



On Tue, May 03, 2022 at 10:36 PM, markmacgillivray ***@***.***

**Comment by markmacgillivray** [comment]
This was done by the way, should be testable

**Comment by JosephMcArthur** [comment]
Thanks, will let them know!

**Comment by JosephMcArthur** [comment]
I've let folks know. One confirmed all was good.

Going to shut hoping the other will too.
