### ISSUE TITLE
Slow permissions responses for JCT

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/discussion#1855]
JCT had some downtime on 19th April, they think caused by permissions responding too slowly. There's not direct evidence of this yet, so it may not be the case, but some investigation was required.

It seems some new JCT code adds a 3s timeout to their requests to permissions, and for some reason the timeout caused their API to crash - there's nothing we can do about this, it's a problem at the JCT end, and not really our concern (the timeout should be caught in a way that doesn't error out the API). However, if it's true that a delay of 3s was the cause, we should find out why it was taking us longer than 3s.

I checked but couldn't get a response that slow myself. However I found an excessive amount of security auditlog indexes that we don't need, caused by different security defaults in the latest version of ES opendistro that we switched to last year. So I deleted those, and that freed up some overhead for the index, and made fresh permissions responses a little bit faster. 

So this issue is just to record work done at this stage, and I'll do a bit more to see if I can find any way to trigger such a slow response. I'll ask Steve at JCT if there's any evidence from their backend errors that I can use to see if the timeouts were caused by delay on our end.

I will also let JCT know they should check they're sending the necessary info and not just falling over on our standard 404 response if we don't get sent it. And I'll see if I can suggest anything to help them catch their error. 

If nothing further comes of this I'll close it next week.

**Comment by JosephMcArthur** [comment]
Thanks. May have more questions for you, but, quick question for you now.
Are JCT using the right domains to hit the workers properly?

**Comment by markmacgillivray** [comment]
They were but they switched back to the old one because they think that helped solve the problem for them.

**Comment by markmacgillivray** [comment]
Calling api.openaccessbutton.org/permissions is faster than calling api.oa.works/permissions the first time it runs (about 1s vs 2s). However after the first call, api.oa.works has it cached and responds within a few ms. But it shouldn't be slower for the first run anyway, since the old api.openaccessbutton.org calls the new api.oa.works backend server anyway. So some investigation is going to be needed here.

Either way, this doesn't show why it took over 3s to respond to JCT requests when they had that issue, and I only see about 1.5 to 2s responses when I test directly. We already know that permissions was designed to be comprehensive rather than fast for that initial calculation, so it may well always take a while for the first time, but worth investigating the discrepancy over the URLs.

JCT are planning to crawl every ISSN and build their own local copy. I've said that answers could differ by ROR, but they're happy to go with just by ISSN. However this means that at least one customer is going to be using the endpoint in a way not well suited to what it was designed for - they're crawling all rather than one, and not needing the comprehensive response anyway. They ask if there is a possibility of a data dump, which also doesn't fit what it was designed for, but should be considered given that they're going to be doing it anyway.

This has been taking a while to work on, sorry about that, so other things may be delayed.

**Comment by markmacgillivray** [comment]
I am going to alter some cloudflare settings on our live API, I'll do it over the weekend to minimise any possible impact on users. Just noting here in case you see alerts over the weekend.

**Comment by JosephMcArthur** [comment]
Thanks Mark. I realize this has taken a bunch of time but I'm glad you were on top of it -- it's important that Gates / JCT get our attention when they need it.

I agree that we should discuss what creating a data dump on end would look like (added to our agenda) –– if they start doing it I suspect we'll end up with all the problems of data dump without the control to address issues efficiently.

I'd be interested in knowing if there are any parts of the algorithm that are slowing down our first responses. I think we've discussed this before (and confirm that, for instance, we don't make any remote calls) but it still feels like the first response is a little slower than I'd expect.

**Comment by JosephMcArthur** [comment]
Update from today:

- [ ] Joe to tell JCT they can make a data-dump, but, there’s no guarantees for us (as this avoids needing to make dump now for us but gives them what they want)
- [ ] Joe to tell JCT they can use api.openaccessbutton if they want (as this avoids resolving worker issue urgently)
- [ ] Joe to make issue to look into performance issues for permissions ISSNs
- [X] Joe to check if we have an SLA with them

We don't have an SLA -- inform them we're happy to sign one if they wish.

- [ ] Joe to remove JCT direct access to Mark, go through me on all occasions 
- [ ] Joe to make an issue to consider making an endpoint for performance monitoring uncached first time uses (mark suggests a duplicate route with auth via API key and no caching)

@markmacgillivray, is there any outstanding work you need to do here? Otherwise I'll unassign. Having your text update here wouldn't be a bad thing for posterity.

**Comment by markmacgillivray** [comment]
I'll change cloudflare configs once the cert is available (it maybe already is, I haven't checked today). 

My update was that proxying the bg with cloudlfare may make a small difference, but the most difference is likely because an endpoint like permissions makes multiple index requests on the first call. We could improve that by grouping them together, or passing the whole process to bg (but then making it less resilient). We could also check to see if there is some reason inherent to the code which makes it run slower on cloudflare than it does on our server. However none of these things are necessary, just options. The purpose of permissions was not to be as fast as possible but to be as comprehensive as possible, and it caches the first calculation, so these improvements are not our highest priority.
