### ISSUE TITLE
InstantILL set up page doesn't provide config

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1857]
**Describe the bug**

https://openaccessbutton.org/instantill/setup#embed doesn't provide functional embed codes (seems to be missing config)

**To Reproduce**
1. Go to https://openaccessbutton.org/instantill/setup
2. Sign in
3. Change any settings
4. Go to https://openaccessbutton.org/instantill/setup
5. Embed something with:

```
<div id="instantill"></div>
<script src="https://instantill.org/embed.js"></script>
<script>_oab=instantill({uid: "h9mTMgqeaKDyJW8E2", config: });</script>
```

6. Embed won't work

**Expected behavior**

`config:` should provide your settings.

**Other information**

Not tested with SYP

**Comment by JosephMcArthur** [comment]
Thanks for the update –– if you could do that would be fab

**Comment by markmacgillivray** [comment]
Done
